

# Site settings
title: Testing title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A lonely meme floats gently in the wind... what does it have to say....
baseurl: "" # the subpath of your site, e.g. /blog
url: "murdiff.com" # the base hostname & protocol for your site
github_username:  murdiff

# Build settings
markdown: kramdown
