# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Testing title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A lonely meme floats gently in the wind... what does it have to say....
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  jekyll

# Build settings
markdown: kramdown
